FROM gradle:jdk17

# Copy the WAR file to the webapps directory
COPY react-and-spring-data-rest-basic-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

CMD ["java", "-jar", "react-and-spring-data-rest-basic-0.0.1-SNAPSHOT.jar"]
