pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out...'
                git branch: 'main', url: 'https://github.com/ASofiaRocha/DeVops-23-24-PSM-1231867.git'
            }
        }

        stage('Assemble') {
            steps {
                dir('CA2/Part2/react-and-spring-data-rest-basic') {
                    echo 'Assembling...'
                    sh 'chmod +x gradlew'
                    sh './gradlew clean assemble'
                }
            }
        }

        stage('Test') {
            steps {
                dir('CA2/Part2/react-and-spring-data-rest-basic') {
                    echo 'Testing...'
                    sh './gradlew test'
                    junit 'build/test-results/test/*.xml'
                }
            }
        }

        stage('Javadoc') {
            steps {
                dir('CA2/Part2/react-and-spring-data-rest-basic') {
                    echo 'Generating Javadocs...'
                    sh './gradlew javadoc'
                    publishHTML(target: [
                            reportDir  : 'build/docs/javadoc',
                            reportFiles: 'index.html',
                            reportName : 'Javadoc'])
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('CA2/Part2/react-and-spring-data-rest-basic') {
                    echo 'Building Docker Image...'
                    script {
                        def dockerhubToken = credentials('CA5')
                        def imageName = "${dockerhubToken_USR}/CA5-jenkins-docker-react-basic"
                        dockerImage = docker.build("${imageName}:${env.BUILD_NUMBER}", "-f Dockerfile .")
                    }
                }
            }
        }

        stage('Docker Login') {
            steps {
                echo 'Logging in to Docker Hub...'
                script {
                    def dockerhubToken = credentials('CA5')
                    sh "echo ${dockerhubToken_PSW} | docker login -u ${dockerhubToken_USR} --password-stdin"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                echo 'Pushing Docker Image...'
                script {
                    def dockerhubToken = credentials('CA5')
                    def imageName = "${dockerhubToken_USR}/CA5-jenkins-docker-react-basic"
                    sh "docker push ${imageName}:${env.BUILD_NUMBER}"
                }
            }
        }

        stage('Archiving') {
            steps {
                dir('CA2/Part2/react-and-spring-data-rest-basic') {
                    echo 'Archiving...'
                    archiveArtifacts 'build/libs/*'
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            script {
                def dockerhubToken = credentials('CA5')
                def imageName = "${dockerhubToken_USR}/CA5-jenkins-docker-react-basic"
                sh "docker rmi ${imageName}:${env.BUILD_NUMBER}"
                sh 'docker logout'
            }
        }
    }
}
